version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_DB: "fitness"
      POSTGRES_USER: "fitness-user"
      POSTGRES_PASSWORD: "io0Jae0oOhl7eeF5"
      PGDATA: /data/postgres
    ports:
      - '5431:5432'
    volumes:
      - postgres:/data/postgres
      - ./scripts/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql

volumes:
  postgres:
